/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.cajero.interfaz;

import co.cajero.bean.Cliente;
import co.cajero.bean.General;
import javax.swing.JOptionPane;

/**
 *
 * @author TabSan
 */
public class FrmCajeroOpciones extends javax.swing.JFrame {
    
    Cliente cliente=null;
    
    
    
    /**
     * Creates new form FrmCajeroOpciones
     */
    public FrmCajeroOpciones() {
        initComponents();
    }
    public FrmCajeroOpciones(Cliente cliente){
        this.cliente=cliente;
        initComponents();
        cargarDatosPantalla();
    }
    
    void cargarDatosPantalla(){
        lblBienvenida.setText("Bienvenido(a) "+cliente.getNombreCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        btnConsultarSaldo = new javax.swing.JButton();
        btbRetiro10 = new javax.swing.JButton();
        btnRetiro20 = new javax.swing.JButton();
        btnRetiro50 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido");

        btnConsultarSaldo.setText("Consultar Saldo");
        btnConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarSaldoActionPerformed(evt);
            }
        });

        btbRetiro10.setText("Retiro $10");
        btbRetiro10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbRetiro10ActionPerformed(evt);
            }
        });

        btnRetiro20.setText("Retiro $20");
        btnRetiro20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiro20ActionPerformed(evt);
            }
        });

        btnRetiro50.setText("Retiro $50");
        btnRetiro50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiro50ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btbRetiro10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetiro20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetiro50, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblBienvenida)
                .addGap(29, 29, 29)
                .addComponent(btbRetiro10)
                .addGap(18, 18, 18)
                .addComponent(btnRetiro20)
                .addGap(18, 18, 18)
                .addComponent(btnRetiro50)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarSaldo)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarSaldoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Su saldo es $"+cliente.getSaldo(), "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnConsultarSaldoActionPerformed

    private void btbRetiro10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbRetiro10ActionPerformed
        retirar(10);
    }//GEN-LAST:event_btbRetiro10ActionPerformed

    private void btnRetiro20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiro20ActionPerformed
        retirar(20);
    }//GEN-LAST:event_btnRetiro20ActionPerformed

    private void btnRetiro50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiro50ActionPerformed
        retirar(50);
    }//GEN-LAST:event_btnRetiro50ActionPerformed
// Cuando el formulario se ciere, se guarda la info <- Para persistencia
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //General.general.guardar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCajeroOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCajeroOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCajeroOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCajeroOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCajeroOpciones().setVisible(true);
            }
        });
    }
    
    private void retirar(float dinero){
        boolean sw=General.getCajero().retirar(cliente, dinero);
        if(sw){//Si el dinero fue retirado
            JOptionPane.showMessageDialog(rootPane, "Retiro exitoso");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Fondos insuficientes");
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbRetiro10;
    private javax.swing.JButton btnConsultarSaldo;
    private javax.swing.JButton btnRetiro20;
    private javax.swing.JButton btnRetiro50;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
